"""
Working memory buffer for UMA-3.

This module implements an in-memory, per-user working memory buffer that stores
recent conversation turns (user + assistant messages). It is responsible for:

- Keeping an ordered list of messages per user/session.
- Providing an estimated token usage (for context window management).
- Exposing safe methods to append messages and retrieve the current context.

This module does NOT:
- Perform summarization or eviction itself.
- Talk to any long-term memory store (episodic/semantic).

Those responsibilities belong to QueueManager and Summarizer.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Dict, List, Literal, Optional

logger = logging.getLogger(__name__)


Role = Literal["user", "assistant", "system", "summary"]


@dataclass
class WorkingMemoryMessage:
    """
    Represents a single message in working memory.

    Attributes
    ----------
    role:
        The role that produced the message.
        Common values: "user", "assistant", "system", "summary".
        "summary" messages are synthetic summaries generated by UMA-3.

    content:
        Raw text content of the message.

    token_estimate:
        Approximate number of tokens for this message.
        This is an estimate only and is used for budgeting.
        It can be computed by a simple heuristic or a proper tokenizer.

    metadata:
        Optional free-form metadata. For example:
        - {"source": "llm", "turn_id": "t123"}
        - {"summary_of": [0, 1, 2]}  # indices of messages summarized
    """

    role: Role
    content: str
    token_estimate: int
    metadata: Optional[dict] = None


class WorkingMemoryBuffer:
    """
    Per-user working memory buffer.

    This class is intentionally simple and generic. It does not depend on any
    specific LLM or store implementation.

    Responsibilities
    ----------------
    - Maintain an ordered list of WorkingMemoryMessage objects per user.
    - Provide methods to append messages.
    - Provide a method to retrieve the current context for a user.
    - Provide a method to estimate total token usage.

    Error handling
    --------------
    - Raises ValueError for invalid roles or empty content.
    - Logs operations at DEBUG level for tracing.
    """

    def __init__(self, max_tokens: int) -> None:
        """
        Parameters
        ----------
        max_tokens:
            Soft maximum number of tokens allowed per user's working memory.
            Enforcement is handled by QueueManager/Summarizer; this class
            only exposes the current usage.
        """
        self._max_tokens = max_tokens
        self._store: Dict[str, List[WorkingMemoryMessage]] = {}
        logger.info("Initialized WorkingMemoryBuffer with max_tokens=%d", max_tokens)

    @property
    def max_tokens(self) -> int:
        """Return the configured soft token limit."""
        return self._max_tokens

    def _estimate_tokens(self, text: str) -> int:
        """
        Estimate token count for a piece of text.

        Implementation note
        --------------------
        This is a heuristic implementation: number of whitespace-separated
        tokens multiplied by a constant factor. In a production system, you
        should replace this with a real tokenizer (e.g., tiktoken).

        Returns
        -------
        int
            Estimated token count.
        """
        # Simple heuristic: word count * 1.3 (rough guess)
        word_count = len(text.split())
        return max(1, int(word_count * 1.3))

    def append(
        self,
        user_id: str,
        role: Role,
        content: str,
        metadata: Optional[dict] = None,
        token_estimate: Optional[int] = None,
    ) -> WorkingMemoryMessage:
        """
        Append a message to a user's working memory.

        Parameters
        ----------
        user_id:
            Identifier for the user/session.
        role:
            One of "user", "assistant", "system", "summary".
        content:
            Message text. Must be non-empty.
        metadata:
            Optional metadata to attach.
        token_estimate:
            Optional explicit token count override. If None, a heuristic
            estimate will be computed.

        Returns
        -------
        WorkingMemoryMessage
            The message instance that was stored.

        Raises
        ------
        ValueError
            If content is empty or role is invalid.
        """
        if not content:
            raise ValueError("WorkingMemoryBuffer.append: content must be non-empty")

        if role not in ("user", "assistant", "system", "summary"):
            raise ValueError(f"WorkingMemoryBuffer.append: invalid role '{role}'")

        if token_estimate is None:
            token_estimate = self._estimate_tokens(content)

        msg = WorkingMemoryMessage(
            role=role,
            content=content,
            token_estimate=token_estimate,
            metadata=metadata,
        )

        self._store.setdefault(user_id, []).append(msg)

        logger.debug(
            "Appended message to working memory: user_id=%s role=%s tokens=%d",
            user_id,
            role,
            token_estimate,
        )

        return msg

    def get_context(self, user_id: str) -> List[WorkingMemoryMessage]:
        """
        Return the current working memory messages for a user.

        Notes
        -----
        - The returned list is a shallow copy; modifying it will not mutate
          the internal buffer.
        - Consumers should not rely on object identity stability.

        Returns
        -------
        list[WorkingMemoryMessage]
            List of messages in insertion order for this user.
        """
        messages = self._store.get(user_id, [])
        # Return a copy to avoid accidental external mutation.
        return list(messages)

    def total_tokens(self, user_id: str) -> int:
        """
        Compute approximate total token usage for a user's working memory.

        Returns
        -------
        int
            Sum of token_estimate for all messages for the user.
        """
        total = sum(msg.token_estimate for msg in self._store.get(user_id, []))
        logger.debug(
            "Total tokens for user_id=%s in working memory: %d",
            user_id,
            total,
        )
        return total

    def replace_messages(
        self,
        user_id: str,
        new_messages: List[WorkingMemoryMessage],
    ) -> None:
        """
        Replace the entire message list for a user.

        This is primarily used by summarization logic:
        - Summarizer may collapse older messages into a single summary message.
        - It prepares a new list and calls this method to swap it in.

        Parameters
        ----------
        user_id:
            User/session identifier.
        new_messages:
            New ordered message list to store for this user.

        Notes
        -----
        - This method overwrites the previous list completely.
        - Callers must ensure new_messages is consistent and valid.
        """
        self._store[user_id] = list(new_messages)
        logger.info(
            "Replaced working memory messages for user_id=%s; new_len=%d",
            user_id,
            len(new_messages),
        )