#!/usr/bin/env python3
"""Remove generated cache, build artifacts, and OS metadata from this repository.

Modes
-----
default        Remove matches, print a summary, exit 0 on success / 1 on error.
--dry-run      Print matches, remove nothing, exit 0.
--verify       Scan-only. Exit 1 if any match found, 0 if clean. Wire this
               into the pre-release / CI gate to prevent __MACOSX, .DS_Store,
               orphaned .pyc, egg-info, build/, dist/, etc. from shipping.
--watch        Repeat cleanup until interrupted (existing behavior preserved).
--caches-only  Remove only regenerable caches (__pycache__, .pytest_cache,
               .ruff_cache, *.pyc, ...). Leaves build outputs (build/, dist/,
               *.egg-info) and coverage artifacts alone. This is the mode the
               test suite runs automatically; the default full mode stays the
               release-hygiene gate.

Root selection
--------------
The repository root is auto-detected by walking up from the script location
looking for a project marker (.git, pyproject.toml, setup.py). Override with
--root. The script refuses to run if the resolved root is not a project root,
so it cannot accidentally scrub an unrelated directory.
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
import time
from pathlib import Path


# ---------------------------------------------------------------------------
# Patterns
# ---------------------------------------------------------------------------
# Directories that we never descend into (their contents are the developer's,
# not ours to touch).
EXCLUDED_DIRS = {".git", ".venv", "venv", "env", "node_modules"}

# Directory names that get removed wherever they appear.
CACHE_DIRS = {
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".eggs",
    "htmlcov",
    ".ipynb_checkpoints",
    "__MACOSX",       # finding #25 — the reason this script exists
    "build",
    "dist",
}

# Build outputs and coverage artifacts: removed by the default release-hygiene
# pass, kept by --caches-only. These are produced deliberately by a build or a
# `pytest --cov` run, so deleting them as a side effect of running tests would
# destroy output the caller is about to use.
NON_CACHE_DIRS = {"build", "dist"}
NON_CACHE_DIR_SUFFIXES = (".egg-info",)
NON_CACHE_FILES = {".coverage", "coverage.xml"}

# Directory-name suffixes that get removed wherever they appear (covers
# arbitrary <pkg>.egg-info directories generated by setuptools).
CACHE_DIR_SUFFIXES = (".egg-info",)

# Exact file names that get removed wherever they appear.
OS_FILES = {".DS_Store", "Thumbs.db", "Desktop.ini", ".coverage", "coverage.xml"}

# File-name suffixes that get removed wherever they appear.
CACHE_SUFFIXES = {".pyc", ".pyo", ".egg"}

# File-name prefixes that get removed wherever they appear (macOS AppleDouble).
CACHE_PREFIXES = ("._",)

# A project root must contain at least one of these; otherwise refuse to run.
PROJECT_MARKERS = (".git", "pyproject.toml", "setup.py")


# ---------------------------------------------------------------------------
# Root detection
# ---------------------------------------------------------------------------
def _looks_like_project_root(path: Path) -> bool:
    return any((path / marker).exists() for marker in PROJECT_MARKERS)


def _autodetect_root(start: Path) -> Path | None:
    """Walk up from ``start`` until a directory with a project marker appears."""
    for candidate in (start, *start.parents):
        if _looks_like_project_root(candidate):
            return candidate
    return None


# ---------------------------------------------------------------------------
# Match classification
# ---------------------------------------------------------------------------
def _dir_matches(name: str, *, caches_only: bool = False) -> bool:
    if caches_only and (name in NON_CACHE_DIRS or name.endswith(NON_CACHE_DIR_SUFFIXES)):
        return False
    return name in CACHE_DIRS or name.endswith(CACHE_DIR_SUFFIXES)


def _file_matches(name: str, *, caches_only: bool = False) -> bool:
    if caches_only and name in NON_CACHE_FILES:
        return False
    if name in OS_FILES:
        return True
    if name.startswith(CACHE_PREFIXES):
        return True
    lower_suffix = Path(name).suffix.lower()
    return lower_suffix in CACHE_SUFFIXES


# ---------------------------------------------------------------------------
# Core walk
# ---------------------------------------------------------------------------
def clean(
    root: Path,
    *,
    dry_run: bool = False,
    verify: bool = False,
    caches_only: bool = False,
) -> tuple[int, int, list[Path]]:
    """Walk ``root`` and act on matches.

    Returns
    -------
    (removed_or_matched, errors, matches)
        ``matches`` is the list of hit paths (relative to ``root``); populated
        in every mode so verify/report can decide what to print.
    """
    removed = 0
    errors = 0
    matches: list[Path] = []

    for current, dirnames, filenames in os.walk(root, topdown=True):
        current_path = Path(current)

        # Prune excluded / dotted-venv subtrees before we recurse into them.
        dirnames[:] = [
            name
            for name in dirnames
            if name not in EXCLUDED_DIRS and not name.startswith(".venv")
        ]

        # Handle cache directories at this level, then stop os.walk from
        # descending into them (removing a dir we're about to walk into is
        # a footgun).
        for name in list(dirnames):
            if not _dir_matches(name, caches_only=caches_only):
                continue
            path = current_path / name
            rel = path.relative_to(root)
            matches.append(rel)
            if verify or dry_run:
                # Verify/dry-run: no mutation, just record + optionally print.
                if dry_run:
                    print(rel)
                removed += 1
            else:
                try:
                    shutil.rmtree(path)
                    removed += 1
                except FileNotFoundError:
                    pass
                except OSError as exc:
                    errors += 1
                    print(f"Could not remove {path}: {exc}", file=sys.stderr)
            dirnames.remove(name)

        # Handle matching files at this level.
        for name in filenames:
            if not _file_matches(name, caches_only=caches_only):
                continue
            path = current_path / name
            rel = path.relative_to(root)
            matches.append(rel)
            if verify or dry_run:
                if dry_run:
                    print(rel)
                removed += 1
            else:
                try:
                    path.unlink(missing_ok=True)
                    removed += 1
                except OSError as exc:
                    errors += 1
                    print(f"Could not remove {path}: {exc}", file=sys.stderr)

    return removed, errors, matches


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Remove repository cache files and OS metadata.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="repository root to clean (default: auto-detect from script location)",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help=(
            "scan-only: exit 1 if any match is found, 0 if clean. "
            "Use this as a pre-release / CI gate."
        ),
    )
    parser.add_argument(
        "--watch",
        action="store_true",
        help="repeat cleanup until interrupted",
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=10.0,
        help="seconds between watch-mode cleanups (default: 10)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="show matches without removing them",
    )
    parser.add_argument(
        "--caches-only",
        action="store_true",
        help=(
            "remove only regenerable caches; leave build/, dist/, *.egg-info "
            "and coverage artifacts in place"
        ),
    )
    args = parser.parse_args()

    if args.interval <= 0:
        parser.error("--interval must be greater than zero")
    if args.verify and args.watch:
        parser.error("--verify and --watch are mutually exclusive")
    if args.verify and args.dry_run:
        # Not fatal but confusing — --verify is already scan-only.
        parser.error("--verify already implies scan-only; drop --dry-run")

    return args


def _resolve_root(explicit: Path | None) -> Path:
    """Resolve and validate the repository root, or exit with a clear error."""
    if explicit is not None:
        root = explicit.resolve()
        if not root.is_dir():
            print(f"cleandir: --root {root} is not a directory", file=sys.stderr)
            sys.exit(2)
    else:
        script_dir = Path(__file__).resolve().parent
        detected = _autodetect_root(script_dir)
        if detected is None:
            print(
                "cleandir: could not auto-detect repository root from "
                f"{script_dir}. Pass --root explicitly.",
                file=sys.stderr,
            )
            sys.exit(2)
        root = detected

    if not _looks_like_project_root(root):
        markers = ", ".join(PROJECT_MARKERS)
        print(
            f"cleandir: refusing to clean {root} — no project marker "
            f"({markers}) found. Pass a real repo root via --root.",
            file=sys.stderr,
        )
        sys.exit(2)

    return root


def main() -> int:
    args = parse_args()
    root = _resolve_root(args.root)

    if args.verify:
        _, errors, matches = clean(root, verify=True, caches_only=args.caches_only)
        if matches:
            print(
                f"cleandir --verify: {len(matches)} disallowed item(s) in {root}:",
                file=sys.stderr,
            )
            for rel in matches:
                print(f"  {rel}", file=sys.stderr)
            print(
                "Run `python cleandir.py` before building the release "
                "archive.",
                file=sys.stderr,
            )
            return 1
        print(f"cleandir --verify: clean ({root}).")
        return 1 if errors else 0

    if args.watch:
        print(f"Watching {root} every {args.interval:g}s; press Ctrl+C to stop.")

    try:
        while True:
            removed, errors, _ = clean(
                root, dry_run=args.dry_run, caches_only=args.caches_only
            )
            if removed or not args.watch:
                action = "Matched" if args.dry_run else "Removed"
                print(f"{action} {removed} item(s); {errors} error(s).")
            if not args.watch:
                return 1 if errors else 0
            time.sleep(args.interval)
    except KeyboardInterrupt:
        print("\nStopped.")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
